### PR TITLE
Feature bootstrap - TSE request

### PR DESCRIPTION
**Pull request by kiptubei**
This project  is a replica of the news site Newsweek.com using the Bootstrap framework.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @kiptubei, great job with this cool project :+1: The UI looks great. However, we need to implement a few changes. Kindly address the comments below:
- Kindly add the ```latest news``` section, it is currently missing
- Kindly add ```Featured slideshow``` it is currently missing
- The page is not responsive both on medium and mobile screen device, let us make the page responsive
- The project requires us to use Bootstrap classes 'everywhere' for styling. Let us reduce the size of our CSS file and also implement the DRY rule
- Let us use the required linter for our stylelint.config.js by using this [link](https://github.com/microverseinc/linters-config/blob/master/css/stylelint.config.js)

KIndly implement these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by kiptubei** [comment]
Hello @addod19 ,
Thanks for the timely review.

We seem to be getting different content on the newseek site,perharps due to regions, there is no `latest news` section on my end:
Screenshot from 2020-05-26 09-37-23

On this issues:
"The page is not responsive both on medium and mobile screen device, let us make the page responsive"

This is what i get on my end:
lg screen 
lg-newsweek

medium screen
md-newsweek

small screen
sm-newsweek

Finally on this issue 

> The project requires us to use Bootstrap classes 'everywhere' for styling

The project requirements are a bit more flexible.. i.e 
> Remember to use Bootstrap CSS classes "wherever" it is possible.

In instances where I have not used bootstrap explicitly for styling, it is simply because either bootstrap does not provide the feature I am looking for ,e.g display:none  , postioning : relative and absolute ,unicode characters etc , or otherwise the level of detail I require for a specific feature e'g text underline color or size. Remember bootstrap is an excellent CSS framework, however it is certainly not a substitute to CSS.

Thanks,
@kiptubei

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @kiptubei, great work with the explanation :+1: However, I cannot approve the project if I the project do not pass the checklist of my review. Kindly check the comments below as a follow up of my review:
- ```On the responsiveness```, kindly check the following screenshots
med
small
horz
This has a horizontal scroll
```On the issue of DRY```, kindly apply the DRY rule as mentioned in the previous review
bdcol
absol
dnone
d-none
fntfam
inline
txtdec
absol
- ```Stylelint```, I gave a link for the stylelint to be used, kindly click on the link and copy the contents of the file and paste it to your stylelint.config.js file
lintz


Kindly work on the comments and submit another code review :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo)

**Comment by kiptubei** [comment]
Hello @addod19 ,

Changes made:

- Improved responsiveness
- Copied microverse stylelint
- Removed CSS duplictaes

Thanks Man,
Mark James Kiptubei

**Review by trekab — CHANGES_REQUESTED** [review]
# Changes Required! :recycle: 
Hi @kiptubei, this is impressive work! You have done a good job with the bootstrap classes. :+1: However, there are some minor issues to fix to complete this project. These are:
- [ ] You still have [HTML validator](https://validator.w3.org/#validate_by_upload) errors.
- [ ] You have various broken images on your clone.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__

**Comment by kiptubei** [comment]
Hello @trekab ,
Thanks so much for the timely review. 
The Warning you are referring to is about use of Unicode to represent the search icon.I actually made a deliberate choice to implement the code in this way. Warning itself.

> Document uses the Unicode Private Use Area(s), which should not be used in publicly exchanged documents. (Charmod C073)

it's about Private Use Area Unicode as part of the [ Character Model](https://www.w3.org/TR/charmod/)l specification written in 2002 and added as a recommendation in 2005, since then use of icons , custom fonts and emoji's (since 2011) has become more prevalent and as such use of PUA' s rather than Latin characters is now the recommended way of representing such characters , references  [here](https://teamtreehouse.com/community/-document-uses-the-unicode-private-use-areas) and [here](https://siteorigin.com/thread/validation-warning-charmod-c073/) , on the server-side end when using characters such as fa-search,fa-facebook, etc from font awesome and other providers it is actually pointing to a PUA Unicode character , thus, in this case, I think the use of the relevant PUA code for the search icon would be acceptable since its actually how that data is transmitted in the first place. Generally, PUA's is how you get to see symbols on browsers and apps like slack, kindle's, e-book readers, etc.

2. In order to create the icon using google icons or font awesome I would have to employ the use of position absolute and relative or floats thus moving this element out of the DOM and potentially causing havoc unnecessarily with the layout. I could use clearfix ,to try and fix the damage caused but remember this is still considered a hack at best [link](https://perishablepress.com/lessons-learned-concerning-the-clearfix-css-hack/) and [link](https://css-tricks.com/snippets/css/clear-fix/).

PHEW! that was a speech  ...  with this in mind and given that developers are given some creative license when it comes to implementation of solutions, I think it would be in line with current practice to ignore this warning in this context.

Finally,
Which broken links?

Thank you.

**Review by trekab — COMMENTED** [review]
Hi @kiptubei, I agree with you about the validator warning. :+1: The warning can be ignored. Thank you for being descriptive with the `speech` :smile: . I apologize for the issue of broken image links. Apparently there was an issue with my connection. Please submit another code review request. This seems to be the fastest way to get feedback now. Thank you.

**Comment by kiptubei** [comment]
Hello @trekab ,

Thanks a lot for the review. I will send a new request immediatley.

**Review by trekab — COMMENTED** [review]
# Approved! :tada: 
Congratulations! You may merge to master. All the best on your next project! :smile: 

__Treasure Kabareebe__

**Pull request merged**
